name: CI

# run on pushes and pull requests to master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# run job
jobs:
  build-jb-and-check-links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout-repository
      uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r ./book/website/requirements.txt
    - name: Build Jupyter-Book
      run: |
        cd ./book/website
        jupyter-book build .
    # - name: Run html proofer
    #   uses: chabad360/htmlproofer@master
    #   with: 
    #     directory: "./book/website/_build/html"
    #     arguments: --assume-extension --disable-external --only_4xx