name: LoremIpsums

on:
  pull_request:
    branches:
      - master

jobs:
  loremipsums-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: List files in PR
      run: |
        URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
        echo "::set-env name=MODIFIED_FILES::${FILES}"
        echo ${MODIFIED_FILES}
    - name: Filter modified files for /book/content/
      run: |
        for FILE in $MODIFIED_FILES ; do
          echo ${FILE}
        done
