name: LoremIpsums

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  loremipsums:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Run Python script to check for rogue "Lorem ipsums"
      working-directory: ./tests
      run: |
        python lorem-ipsums.py
