name: LoremIpsums

on:
  pull_request:
    branches:
      - master

jobs:
  loremipsums-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: futuratrepadeira/changed-files@v3.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
