# Give your test a name!
name: Prettier

# Decide when to run the tests
#
# This configuration sets the test to run on pushes to master
# and on pull requests that are opened to master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Set up the Continuous Integration job
jobs:
  prettier:
    # Run on the latest Ubuntu distribution
    runs-on: ubuntu-latest
    # This section collects together the steps involved in running the test
    steps:
    # Checkout the repository. Relies on another GH-Action.
    - uses: actions/checkout@v2
    # Install node for install prettier. Relies on another GH-Action.
    - name: Install node
      uses: actions/setup-node@v1.1.0
      with:
        version: 10.x
    # Install the prettier package
    - name: Install prettier
      run: |
        npm install --global prettier
    # Run prettier on markdown files (two steps)
    - name: Check for markdown auto-formatting clashes with Prettier
      run: |
        prettier --check ./book/content/**/*.md
    - name: Check with Prettier again and preserve prose wrap
      run: |
        prettier --check --prose-wrap preserve ./book/content/**/*.md
